### ISSUE TITLE
Use system timezone

### ISSUE THREAD

**Issue by Eeems** [tenJirka/reGenda#4]
If a timezone is not set in the config file, it should default to the system timezone instead of UTC. You can check the value of the `TZ` environment variable, or parse the output of [timedatectl](https://www.man7.org/linux/man-pages/man1/timedatectl.1.html) to determine what the current timezone is set to. This doesn't match what is in xochitl, but it is used by other applications.

https://remarkable.guide/guide/config/timezone.html

**Comment by tenJirka** [comment]
Should be fixed in b7e73456ae9111cc3cba58a7830bfe774d57627b.
